// Mock service data — 17 services from PSM MCP inventory
const SERVICES = [
  {
    id: 'nvidia-codereview',
    name: 'nvidia-codereview',
    displayName: 'NVIDIA Code Review (253B Model)',
    description: 'AI-powered code review using NVIDIA\'s 253B parameter model. Detects bugs, security vulnerabilities, performance issues, and style violations across 40+ languages.',
    category: 'AI',
    price: 0.03,
    tools: 20,
    toolsList: [
      { name: 'nvidia_codereview', desc: 'Full code review with severity grading' },
      { name: 'nvidia_scan', desc: 'Security vulnerability scanner' },
      { name: 'nvidia_quality', desc: 'Code quality scoring (0-100)' },
      { name: 'nvidia_compare', desc: 'Semantic diff between code versions' },
      { name: 'nvidia_ladder', desc: 'Benchmark across Nemotron family' },
      { name: 'nvidia_router', desc: 'Auto-classify and route to best model' },
      { name: 'nvidia_reward', desc: 'Reward model scoring' },
      { name: 'nvidia_guardrails', desc: 'Content safety guardrails' },
      { name: 'nvidia_pii', desc: 'PII detection and redaction' },
      { name: 'nvidia_detect', desc: 'Object/pattern detection' },
      { name: 'nvidia_ocr', desc: 'Text extraction from images' },
      { name: 'nvidia_parse', desc: 'Document structure parsing' },
      { name: 'nvidia_translate', desc: 'Multi-language translation' },
      { name: 'nvidia_multimodal', desc: 'Multimodal analysis' },
      { name: 'nvidia_finance', desc: 'Financial document analysis' },
      { name: 'nvidia_video', desc: 'Video frame analysis' },
      { name: 'nvidia_podcast', desc: 'Audio content processing' },
      { name: 'nvidia_rag', desc: 'Retrieval-augmented generation' },
      { name: 'nvidia_research', desc: 'Deep research synthesis' },
      { name: 'nvidia_safety', desc: 'Content safety moderation' },
    ],
    reputation: 4.7,
    latency: 2400,
    calls: 15400,
    uptime: 99.2,
    gateway: 'https://nim.purplesquirrelmedia.io/codereview',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'nvidia-safety',
    name: 'nvidia-safety',
    displayName: 'NVIDIA Content Safety',
    description: 'Content safety moderation powered by NVIDIA NIM. Screens text, images, and code for harmful content, hate speech, and policy violations.',
    category: 'AI',
    price: 0.01,
    tools: 5,
    toolsList: [
      { name: 'nvidia_safety', desc: 'Content safety classification' },
      { name: 'nvidia_guardrails', desc: 'Policy enforcement guardrails' },
      { name: 'nvidia_pii', desc: 'PII detection' },
      { name: 'nvidia_detect', desc: 'Harmful content detection' },
      { name: 'nvidia_quality', desc: 'Quality scoring with safety overlay' },
    ],
    reputation: 4.9,
    latency: 800,
    calls: 42300,
    uptime: 99.8,
    gateway: 'https://nim.purplesquirrelmedia.io/safety',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'nvidia-research',
    name: 'nvidia-research',
    displayName: 'NVIDIA Deep Research',
    description: 'Multi-model research synthesis across 189 NIM models. Generates evidence-based analysis from multiple AI perspectives with citation tracking.',
    category: 'AI',
    price: 0.05,
    tools: 8,
    toolsList: [
      { name: 'nvidia_research', desc: 'Deep research synthesis' },
      { name: 'nvidia_rag', desc: 'Retrieval-augmented generation' },
      { name: 'nvidia_compare', desc: 'Cross-model comparison' },
      { name: 'nvidia_quality', desc: 'Research quality scoring' },
      { name: 'nvidia_translate', desc: 'Multi-language research' },
      { name: 'nvidia_parse', desc: 'Source document parsing' },
      { name: 'nvidia_ladder', desc: 'Multi-tier model benchmarking' },
      { name: 'nvidia_router', desc: 'Intelligent model routing' },
    ],
    reputation: 4.5,
    latency: 5000,
    calls: 8700,
    uptime: 98.5,
    gateway: 'https://nim.purplesquirrelmedia.io/research',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'sui-mcp',
    name: 'sui-mcp',
    displayName: 'Sui Blockchain Operations',
    description: 'Full Sui blockchain access — wallets, tokens, DeFi, staking, Move calls, SuiNS resolution. GraphQL + JSON-RPC dual transport.',
    category: 'Blockchain',
    price: 0.02,
    tools: 53,
    toolsList: [
      { name: 'get_balance', desc: 'Query SUI balance' },
      { name: 'transfer_sui', desc: 'Transfer SUI tokens' },
      { name: 'move_call', desc: 'Execute Move smart contract calls' },
      { name: 'get_object', desc: 'Fetch on-chain objects' },
      { name: 'swap_quote', desc: 'DEX swap quotes' },
    ],
    reputation: 4.8,
    latency: 350,
    calls: 31200,
    uptime: 99.5,
    gateway: 'https://sui.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'sdp-mcp',
    name: 'sdp-mcp',
    displayName: 'Solana Developer Platform',
    description: 'Complete Solana Developer Platform integration — wallets, payments, stablecoins, tokenization, compliance, issuance, and project management.',
    category: 'Blockchain',
    price: 0.03,
    tools: 76,
    toolsList: [
      { name: 'sdp_wallet_create', desc: 'Create managed wallets' },
      { name: 'sdp_transfer_stablecoin', desc: 'Transfer USDC/USDT' },
      { name: 'sdp_execute_swap', desc: 'Token swaps' },
      { name: 'sdp_issuance_deploy_token', desc: 'Deploy new tokens' },
      { name: 'sdp_compliance_screen_address', desc: 'Compliance screening' },
    ],
    reputation: 4.6,
    latency: 600,
    calls: 22800,
    uptime: 99.1,
    gateway: 'https://sdp.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'solana-mcp',
    name: 'solana-mcp',
    displayName: 'Solana Blockchain',
    description: 'Core Solana blockchain operations — SPL tokens, transfers, account info, staking, token-2022 program support.',
    category: 'Blockchain',
    price: 0.01,
    tools: 25,
    toolsList: [
      { name: 'get_balance', desc: 'SOL balance query' },
      { name: 'transfer_sol', desc: 'Transfer SOL' },
      { name: 'create_spl_token', desc: 'Create SPL tokens' },
      { name: 'mint_tokens', desc: 'Mint tokens' },
      { name: 'get_token_accounts', desc: 'Token account listing' },
    ],
    reputation: 4.4,
    latency: 400,
    calls: 50200,
    uptime: 99.7,
    gateway: 'https://solana.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'ordinals-mcp',
    name: 'ordinals-mcp',
    displayName: 'Bitcoin Ordinals',
    description: 'Bitcoin ordinals and inscriptions — BRC-20 tokens, Runes, rare sats, collections, and marketplace data.',
    category: 'Blockchain',
    price: 0.02,
    tools: 22,
    toolsList: [
      { name: 'get_inscription', desc: 'Fetch inscription details' },
      { name: 'get_brc20_token', desc: 'BRC-20 token info' },
      { name: 'get_rune_info', desc: 'Rune details' },
      { name: 'search_inscriptions', desc: 'Search inscriptions' },
      { name: 'get_sat_info', desc: 'Satoshi rarity info' },
    ],
    reputation: 4.3,
    latency: 900,
    calls: 12100,
    uptime: 98.8,
    gateway: 'https://ordinals.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'coldstar-mcp',
    name: 'coldstar-mcp',
    displayName: 'Coldstar Air-Gapped Wallet',
    description: 'Air-gapped cold wallet operations — custody management, Ed25519 signing verification, vault status, multi-chain portfolio tracking.',
    category: 'Blockchain',
    price: 0.05,
    tools: 22,
    toolsList: [
      { name: 'check_wallet_balance', desc: 'Cold wallet balance' },
      { name: 'validate_transaction', desc: 'Transaction validation' },
      { name: 'verify_ed25519_signature', desc: 'Signature verification' },
      { name: 'get_vault_status', desc: 'Vault health status' },
      { name: 'create_custody_request', desc: 'Custody transfer request' },
    ],
    reputation: 5.0,
    latency: 200,
    calls: 4800,
    uptime: 99.9,
    gateway: 'https://coldstar.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'ai-music-mcp',
    name: 'ai-music-mcp',
    displayName: 'AI Music Generation',
    description: 'Full music production pipeline — MusicGen composition, Demucs stem separation, RVC voice conversion, format conversion.',
    category: 'Media',
    price: 0.25,
    tools: 8,
    toolsList: [
      { name: 'music_generate', desc: 'Generate music from text prompt' },
      { name: 'music_separate_stems', desc: 'Separate audio stems' },
      { name: 'music_convert_voice', desc: 'RVC voice conversion' },
      { name: 'music_full_pipeline', desc: 'End-to-end pipeline' },
      { name: 'music_get_info', desc: 'Audio file info' },
      { name: 'music_list_files', desc: 'List generated files' },
      { name: 'music_list_stems', desc: 'List separated stems' },
      { name: 'music_list_voice_models', desc: 'Available voice models' },
    ],
    reputation: 4.2,
    latency: 4500,
    calls: 3200,
    uptime: 96.5,
    gateway: 'https://music.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'videoskill-mcp',
    name: 'videoskill-mcp',
    displayName: 'Video Processing Pipeline',
    description: 'Narrated video to structured content — transcription, frame extraction, skill step generation, timeline alignment, markdown rendering.',
    category: 'Media',
    price: 0.10,
    tools: 16,
    toolsList: [
      { name: 'video_transcribe', desc: 'Audio transcription' },
      { name: 'video_extract_frames', desc: 'Key frame extraction' },
      { name: 'video_extract_steps', desc: 'Skill step extraction' },
      { name: 'video_full_pipeline', desc: 'Complete pipeline run' },
      { name: 'video_render_markdown', desc: 'Markdown output' },
    ],
    reputation: 4.1,
    latency: 3200,
    calls: 5600,
    uptime: 97.2,
    gateway: 'https://video.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'pixelmator-mcp',
    name: 'pixelmator-mcp',
    displayName: 'Pixelmator Image Editing',
    description: 'Professional image editing — auto-enhance, background removal, super resolution, color matching, LUT application, text overlays.',
    category: 'Media',
    price: 0.10,
    tools: 23,
    toolsList: [
      { name: 'pixelmator_auto_enhance', desc: 'ML auto-enhancement' },
      { name: 'pixelmator_remove_background', desc: 'Background removal' },
      { name: 'pixelmator_super_resolution', desc: '4x upscaling' },
      { name: 'pixelmator_crop', desc: 'Intelligent crop' },
      { name: 'pixelmator_resize', desc: 'Resize with resampling' },
    ],
    reputation: 4.4,
    latency: 1800,
    calls: 9300,
    uptime: 98.1,
    gateway: 'https://pixelmator.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'imessage-mcp',
    name: 'imessage-mcp',
    displayName: 'iMessage Automation',
    description: 'iMessage programmatic access — send messages, read conversations, search history, manage contacts, schedule messages, export chats.',
    category: 'Productivity',
    price: 0.01,
    tools: 12,
    toolsList: [
      { name: 'imessage_send', desc: 'Send iMessage' },
      { name: 'imessage_read', desc: 'Read messages' },
      { name: 'imessage_search', desc: 'Search message history' },
      { name: 'imessage_schedule', desc: 'Schedule future messages' },
      { name: 'imessage_export', desc: 'Export conversations' },
    ],
    reputation: 4.6,
    latency: 300,
    calls: 28500,
    uptime: 99.4,
    gateway: 'https://imessage.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'macos-mcp',
    name: 'macos-mcp',
    displayName: 'macOS System Control',
    description: 'macOS automation — FaceTime, Contacts, Notes, Reminders, Safari, Music, Finder/AirDrop, system brightness, WiFi, phone calls.',
    category: 'Productivity',
    price: 0.01,
    tools: 20,
    toolsList: [
      { name: 'safari_open', desc: 'Open Safari URL' },
      { name: 'notes_create', desc: 'Create Apple Note' },
      { name: 'reminders_create', desc: 'Create reminder' },
      { name: 'contacts_search', desc: 'Search contacts' },
      { name: 'music_play_pause', desc: 'Music playback control' },
    ],
    reputation: 4.3,
    latency: 250,
    calls: 19800,
    uptime: 99.6,
    gateway: 'https://macos.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'apple-calendar-mcp',
    name: 'apple-calendar-mcp',
    displayName: 'Apple Calendar Management',
    description: 'Calendar automation — create events, search across calendars, find availability, manage recurring events.',
    category: 'Productivity',
    price: 0.01,
    tools: 7,
    toolsList: [
      { name: 'calendar_create_event', desc: 'Create calendar event' },
      { name: 'calendar_events_today', desc: 'Today\'s events' },
      { name: 'calendar_search', desc: 'Search events' },
      { name: 'calendar_upcoming', desc: 'Upcoming events' },
      { name: 'calendar_list', desc: 'List calendars' },
      { name: 'calendar_events_range', desc: 'Events in date range' },
      { name: 'calendar_delete_event', desc: 'Delete event' },
    ],
    reputation: 4.5,
    latency: 280,
    calls: 14200,
    uptime: 99.3,
    gateway: 'https://calendar.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'cpanel-mcp',
    name: 'cpanel-mcp',
    displayName: 'cPanel Web Hosting',
    description: 'Complete cPanel/WHM management — domains, DNS, email, MySQL, FTP, SSL, PHP, file management, backups, cron jobs.',
    category: 'Infrastructure',
    price: 0.02,
    tools: 47,
    toolsList: [
      { name: 'cpanel_domains_list', desc: 'List hosted domains' },
      { name: 'cpanel_dns_get_records', desc: 'DNS records' },
      { name: 'cpanel_email_create_account', desc: 'Create email account' },
      { name: 'cpanel_mysql_create_database', desc: 'Create database' },
      { name: 'cpanel_ssl_list_certs', desc: 'SSL certificates' },
    ],
    reputation: 4.0,
    latency: 1200,
    calls: 7600,
    uptime: 98.9,
    gateway: 'https://cpanel.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'psm-mcp-gateway',
    name: 'psm-mcp-gateway',
    displayName: 'MCP Security Gateway',
    description: 'Security proxy for all MCP traffic — rate limiting, authentication, request signing, audit logging, policy enforcement.',
    category: 'Security',
    price: 0.001,
    tools: 4,
    toolsList: [
      { name: 'gateway_status', desc: 'Gateway health check' },
      { name: 'gateway_policy_list', desc: 'Active security policies' },
      { name: 'gateway_audit_log', desc: 'Request audit trail' },
      { name: 'gateway_rate_status', desc: 'Rate limit status' },
    ],
    reputation: 4.8,
    latency: 50,
    calls: 48900,
    uptime: 99.9,
    gateway: 'https://gateway.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
  {
    id: 'kino-mcp',
    name: 'kino-mcp',
    displayName: 'Kino Video Stream Analysis',
    description: 'Live video stream analysis — quality monitoring, content auto-tagging, audio fingerprinting, encoding, stream comparison.',
    category: 'Media',
    price: 0.05,
    tools: 8,
    toolsList: [
      { name: 'analyze_stream', desc: 'Analyze video stream' },
      { name: 'monitor_stream', desc: 'Live stream monitoring' },
      { name: 'autotag_content', desc: 'Auto-tag video content' },
      { name: 'quality_check', desc: 'Stream quality check' },
      { name: 'encode_video', desc: 'Video encoding' },
      { name: 'fingerprint_audio', desc: 'Audio fingerprinting' },
      { name: 'compare_streams', desc: 'Stream comparison' },
      { name: 'validate_stream', desc: 'Stream validation' },
    ],
    reputation: 3.9,
    latency: 1500,
    calls: 2100,
    uptime: 95.8,
    gateway: 'https://kino.purplesquirrelmedia.io/mcp',
    paymentAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  },
];

const CATEGORIES = [
  { id: 'all', name: 'All', count: SERVICES.length },
  { id: 'AI', name: 'AI', count: SERVICES.filter(s => s.category === 'AI').length },
  { id: 'Blockchain', name: 'Blockchain', count: SERVICES.filter(s => s.category === 'Blockchain').length },
  { id: 'Media', name: 'Media', count: SERVICES.filter(s => s.category === 'Media').length },
  { id: 'Productivity', name: 'Productivity', count: SERVICES.filter(s => s.category === 'Productivity').length },
  { id: 'Infrastructure', name: 'Infrastructure', count: SERVICES.filter(s => s.category === 'Infrastructure').length },
  { id: 'Security', name: 'Security', count: SERVICES.filter(s => s.category === 'Security').length },
];

// Mock recent transactions
const RECENT_TRANSACTIONS = [
  { service: 'nvidia-safety', caller: 'agent-0x3f...a2', amount: 0.01, timestamp: Date.now() - 120000 },
  { service: 'solana-mcp', caller: 'agent-0x7b...c1', amount: 0.01, timestamp: Date.now() - 340000 },
  { service: 'sdp-mcp', caller: 'agent-0x1a...f8', amount: 0.03, timestamp: Date.now() - 580000 },
  { service: 'sui-mcp', caller: 'agent-0x9d...e4', amount: 0.02, timestamp: Date.now() - 920000 },
  { service: 'imessage-mcp', caller: 'agent-0x5c...b7', amount: 0.01, timestamp: Date.now() - 1200000 },
  { service: 'nvidia-codereview', caller: 'agent-0x2e...d3', amount: 0.03, timestamp: Date.now() - 1800000 },
  { service: 'cpanel-mcp', caller: 'agent-0x8f...a9', amount: 0.02, timestamp: Date.now() - 2400000 },
  { service: 'pixelmator-mcp', caller: 'agent-0x4b...c6', amount: 0.10, timestamp: Date.now() - 3600000 },
  { service: 'coldstar-mcp', caller: 'agent-0x6a...e1', amount: 0.05, timestamp: Date.now() - 5400000 },
  { service: 'psm-mcp-gateway', caller: 'agent-0xf2...b8', amount: 0.001, timestamp: Date.now() - 7200000 },
  { service: 'macos-mcp', caller: 'agent-0xd1...a5', amount: 0.01, timestamp: Date.now() - 9000000 },
  { service: 'ai-music-mcp', caller: 'agent-0x3c...f2', amount: 0.25, timestamp: Date.now() - 10800000 },
];

// Aggregate stats
const MARKETPLACE_STATS = {
  totalServices: SERVICES.length,
  totalTools: SERVICES.reduce((acc, s) => acc + s.tools, 0),
  totalCalls: SERVICES.reduce((acc, s) => acc + s.calls, 0),
  totalVolume: SERVICES.reduce((acc, s) => acc + (s.calls * s.price), 0),
  avgUptime: (SERVICES.reduce((acc, s) => acc + s.uptime, 0) / SERVICES.length).toFixed(1),
  avgLatency: Math.round(SERVICES.reduce((acc, s) => acc + s.latency, 0) / SERVICES.length),
};

export { SERVICES, CATEGORIES, RECENT_TRANSACTIONS, MARKETPLACE_STATS };
